#-------------------------------
# Site Settings
title: æ¶‰
logo: # You can add own logo. For example '/images/logo.png'.
description: #Hilton is a super simple portfolio theme for Jekyll.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Portfolio'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'

    #- title: 'Pages'
    #  submenu:
    #  - url: '/about/'
    #    title: 'About'
    #  - url: '/contact/'
    #    title: 'Contact'
    #  - url: '/elements/'
    #    title: 'Elements'


#-------------------------------
# Author Settings
author:
  author__name: Tianbai Xiao
  author__bio: Computational physics
  author__avatar: '/images/01.jpg'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/vavrines"}
- {icon: "ion-logo-github", link: "https://github.com/vavrines"}
- {icon: "ion-logo-instagram", link: "https://instagram.com/vavrines"}

#-------------------------------
# Hero Settings
hero:
  hero__title: Tianbai Xiao
  hero__description: Working to create pieces in computational physics, programming and fine arts. Enthusiast of Debussy. Sometimes I do photography.
  hero__image: '/images/leaf.jpg'


#-------------------------------
# Newsletter
mailchimp: diable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Your email address...
mailchimp__button__text: Get in Touch 


#-------------------------------
# Projects Settings
projects__settings:
  projects__title: Portfolio
  projects__description: #I shows only the best websites and portfolios built completely with passion, simplicity & creativity!


#-------------------------------
# Testimonials Section
testimonial__title: What clients say
testimonial__description:

testimonial__items:
  - name: "Aspen Carder"
    image: "/images/client-1.jpg"
    designation: "Lettering Artist"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Lydia Siphron"
    image: "/images/client-2.jpg"
    designation: "Designer"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Craig Vaccaro"
    image: "/images/client-3.jpg"
    designation: "Web developer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Anika Calzoni"
    image: "/images/client-4.jpg"
    designation: "Lettering Artist"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Marcus Botosh"
    image: "/images/client-5.jpg"
    designation: "Full Stack Designer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"


#-------------------------------
# Blog Section
blog__settings:
  blog__title: Blog
  blog__description:


#-------------------------------
# Gallery Footer Settings
gallery:
  gallery__images:
    - alt: 'Rest'
      url: '/images/gallery-1.jpg'
    - alt: 'Lifestyle'
      url: '/images/gallery-2.jpg'
    - alt: 'Hobby'
      url: '/images/gallery-3.jpg'
    - alt: 'Notes'
      url: '/images/gallery-4.jpg'


#-------------------------------
# Footer Navigation Settings
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - url: '/about/'
      title: 'About'
    - url: '/contact/'
      title: 'Contact'
    - url: '/elements/'
      title: 'Elements'


#-------------------------------
# Contact Settings
contact:
  email: tianbaixiao@gmail.com
  description: Drop me a line! Give me a small blurb about your project and I'll get back to you in a jiffy. We'll chat to make sure my skills are a good match for what you're looking for. 


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-ZMCY5J682M # Add your GA Tracking Id
